# Default values for python-http-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: anmobor/python-http-server
  tag: latest
  pullPolicy: IfNotPresent

namespace: my-http-server

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "python-http-server-sac"

securityContext: {}

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: python-http-server.192.168.49.2.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  type: ClusterIP
  port: 8000

livenessProbe:
  path: "/health/liveness"
  port: 8000
  initialDelaySeconds: 150
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  path: "/health/readiness"
  port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80