name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Adjust Docker Context Path
        id: set-path
        run: |
          DOCKER_CONTEXT=${{ github.workspace }}/challenge-1/webserver
          ADJUSTED_CONTEXT=${DOCKER_CONTEXT/#$GITHUB_WORKSPACE\/the-real-devops-challenge/$GITHUB_WORKSPACE}
          echo "ADJUSTED_CONTEXT=$ADJUSTED_CONTEXT" >> $GITHUB_ENV # the-real-devops-challenge was repeated in the path it must be a bug.

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.ADJUSTED_CONTEXT }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-http-server:latest